#!/bin/bash

# Usage
[ $# -eq 0 ] && { echo "Usage: $0 <Company name> <dir> 

Then follow the prompt to complete this generation"; exit 1;  }

# Get Job number
printf "Job Number: "
read jobNum

# Get Company name
#printf "Company Name: "
#read companyName
companyName=$1

# Get date today
day=`date "+%B %d, %Y"`

# Get company's goal
printf "Company's Goal: "
read companyGoal

# Generate the file (You should make the file name as the name of the company you're applying)
touch $1
fileName=coverLetter_$1

printf "Job Number: $jobNum\n" >> $fileName
printf "\nAvailability: 4 months (May-August 2021)\n" >> $fileName
printf "\n$day\n" >> $fileName
printf "\nDear Hiring Manager\n" >> $fileName
printf "\nIt is my great pleasure to apply for the Computer Science Co-op role with $companyName as posted internally by the Ryerson Co-op Office. As a 2nd-year Computer Science Co-op student at Ryerson University who is passionate about analyzing problems, learning and analyzing malware for cybersecurity issues, this opportunity caught my attention. With my proven academic excellence and certificate, I am confident that my familiarity with Cybersecurity, Web server networking, Penetration testing knowledge would qualify me as a competitive candidate for this position.\n" >> $fileName

printf "\n$companyName $companyGoal aligns with my passion for computer security. Directly related to the requirements of this role, my main studies focus deeply on ethical hacking and prepared me well to do penetration testing. To prove this matter, I spent 1 year and a half years self-studying and preparing for the OSCP (Offensive Security Certified Professional) certificate, which focuses heavily on penetration testing and writing reports. During this time, I managed to analyze and hack into a phishing website, which then exposed the list of victims who fell into this trap to provide their login credentials. I retrieved 3500 victims' login credentials and made a short video clip out of it to raise awareness for the community, which reached up to 1200 viewers. As a Co-op student, I would love to contribute my understanding and skill in terms of protecting clients and implementing safety measures to fight against data breaches and system severity.\n" >> $fileName
printf "\nThank you for your time and consideration. With the details listed above that I can bring to $companyName, I have the commitment and a strong passion for security to succeed as a Co-op student. I would appreciate the chance to meet with you to speak more about this opportunity. 
Sincerely,\n
" >> $fileName

echo "Phuc Hua" >> $fileName

mkdir $2

pdf $fileName $fileName.pdf

mv $fileName.pdf $2

rm $fileName

echo "Making Files for company: $companyName"
