#!/bin/bash

# Check if certain kw found in Job Posting
printf "\nPlease provide Company Requirement \nOnce done, press Ctrl + D\n"

input=$(cat)

echo $input > rec

# Keywords files.
qa=QAKey
web=webKey
security=secKey
dev=devKey

# Must include Keywords script
secCount=`keywords rec $security`
webCount=`keywords rec $web`
qaCount=`keywords rec $qa`
devCount=`keywords rec $dev`

printf "
========Job Matches========\n
SoftDev matches:  $devCount\n
Security matches: $secCount\n
QA matches:       $qaCount\n
WebDev matches:   $webCount\n
===========================\n"
