#!/bin/bash
cat .files/banner
# Check if certain kw found in Job Posting
printf "\nPlease provide Company Requirement \nOnce done, press Ctrl + D\n"

input=$(cat)

touch rec
echo $input > rec

# Keywords files.
qa=.files/QAKey
web=.files/webKey
security=.files/secKey
dev=.files/devKey

# Must include Keywords script
secCount=`.files/keywords rec $security`
webCount=`.files/keywords rec $web`
qaCount=`.files/keywords rec $qa`
devCount=`.files/keywords rec $dev`

printf "
========Job Matches========\n
SoftDev matches:  $devCount\n
Security matches: $secCount\n
QA matches:       $qaCount\n
WebDev matches:   $webCount\n
===========================\n"

rm rec
