#!/bin/bash

cat .files/banner
touch exper
fileName=.files/exper
if [[ "$#" -eq 0 ]]; then
    printf "\nWould you like to renew your experience or add to the existing list?
\n\n 1) Setting contacts information
\n\n 2) Renew experience (Caution, this will overwrite your existing experience!)
\n\n 3) Adding to exisitng experience list  
\n\n 4) Customizing Profile Summary 
\n\n 5) Clearing Qualification Summary List
\n\n 6) Editing Qualification Summary list
\n\n 7) Setting Education
\n\n 8) Adding keywords list
\n\n 9) Reset whole profile (except keyword list)
\n"
read -r -p "Choose 1,2,3,4,5,6,7 or q to quit: " choice
else
    choice=$1
fi

case "$choice" in
    2)
	echo "Rewriting existing experience file..."
	echo "" > $fileName
	experience
	exit 1
	;;
    3)
	echo "Adding experience"
	experience
	exit 1
	;;
    4)
	read -r -p "Type your profile summary in one line: " pfsum
	echo "$pfsum" > .files/profileSummary
	exit 1
	;;
    1)
	setname
	exit 1
	;;
    5) echo "Clearing qualification Summary list ..."
       echo "" > .files/qualification
       exit 1
       ;;
    6)
	qualilisting
	exit 1
	;;
   
    7)
	edugen 
	exit 1
	;;
    8)
	keys
	exit 1
	;;
    9)
	echo "Reset all profile info..."
	echo "" > .files/profileSummary
	echo "" > .files/exper
	echo "" > .files/eduPart
	echo "" > .files/qualification
	echo "" > .files/profile
	exit 1
	;;
    q)
	exit 1
	;;
esac

echo "Finishing task, run .menu again to set up your resume"
