#!/bin/bash

flag=false
printf "Adding to your Qualification Summary list. Once done type 'done'\n"
while ! $flag; do
    read content
    if [[ "$content" == "done" ]]; then
        flag=true
        break
    fi
    [[ ! -z "$content" ]] && echo "$content" >> .files/qualification
done
