#!/bin/bash

function trap_ctrlc () 
{  
  printf "\nCleaning up...."
  cleaning 2>/dev/null
  exit 2
}

trap "trap_ctrlc" 2

printf "Submit 'Test' for Company name and Testing for folder for easier cleaning process\n
For cover testing, leave all blank\n
=========================\n
Running package checking\n
=========================\n"
package

printf "\n=========================
\nRunning resume checking\n
=========================\n"
resume

printf "=========================\n
\nRunning cover checking\n
=========================\n"
cover

printf "\n=========================
\nRunning kwcheck checking\n
=========================\n"
kwCheck

cleaning
